### ISSUE TITLE
How about applying denser grid to achieve upscaling in the training process?

### ISSUE THREAD

**Issue by TouKaienn** [vishwa91/MINER#1]
Hi, thanks for your excellent work! After going through the paper and the code, I found that the upscaling is implemented by interpolating the previous signal. However, I know that such implicit neural rendering methods can achieve arbitrary resolution reconstruction, so one thing that came to my mind is, why not apply a denser grid to achieve upscaling in the reconstruction process? This is one point I might not understand very well. Thanks again for your brilliant work!

**Comment by vishwa91** [comment]
Thank you for the great question! Our primary focus was to mimic the Laplacian pyramid, so we chose an interpolation approach for upsampling. That said, your observation is absolutely correct -- the right way to upsample would be by sampling a denser grid. If you wish to discuss this further, please email me at vishwanath.saragadam@rice.edu 

Regards.
